<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Jp.ParahumansOfTheWormverse</RootNamespace>
    <AssemblyName>ParahumansOfTheWormverse</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JpSOTMUtilities" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="JpSOTMUtilities">
      <Private>True</Private>
    </Reference>
    <Reference Include="EngineCommon">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Sentinels of the Multiverse\Sentinels_Data\Managed\EngineCommon.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SentinelsEngine">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Sentinels of the Multiverse\Sentinels_Data\Managed\SentinelsEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Sentinels of the Multiverse\Sentinels_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Sentinels of the Multiverse\Sentinels_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DeckLists\**\*.json">
      <LogicalName>Jp.ParahumansOfTheWormverse.DeckLists.%(EmbeddedResource.FileName).json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ModAssets Include="Assets\**\*.txt" />
    <ModAssets Include="Assets\**\*.jpg" />
    <ModAssets Include="Assets\**\*.png" />
    <ModAssets Include="Assets\**\*.json" />
  </ItemGroup>

  <Target Name="SetupModFolder" AfterTargets="Build">
    <Message Text="Setting up mod folder" Importance="high" />
    <Copy SourceFiles="$(TargetPath);$(TargetDir)\JpSOTMUtilities.dll" DestinationFolder="$(SolutionDir)ParahumansOfTheWormverse" SkipUnchangedFiles="True" />
    <Copy SourceFiles="@(ModAssets)" DestinationFiles="@(ModAssets->'$(SolutionDir)ParahumansOfTheWormverse\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="True" />
  </Target>

  <Target Name="CleanModFolder" BeforeTargets="CoreClean">
    <Message Text="Deleting the mod folder" Importance="high" />
    <RemoveDir Directories="$(SolutionDir)ParahumansOfTheWormverse" />
  </Target>

</Project>
